name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SK_ACCOUNT: ${{ secrets.SK_ACCOUNT }}
          SK_USERNAME: ${{ secrets.SK_USERNAME }}
          SK_ROLE: ${{ secrets.SK_ROLE }}
          SK_WAREHOUSE: ${{ secrets.SK_WAREHOUSE }}
          SK_DATABASE: ${{ secrets.SK_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SK_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          C:/Users/UX508257/AppData/Local/Programs/Python/Python311/python --version
          echo "Step 1: Installing schemachange"
          C:/Users/UX508257/AppData/Local/Programs/Python/Python311/Scripts/pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SK_ACCOUNT -u $SK_USERNAME -r $SK_ROLE -w $SK_WAREHOUSE -d $SK_DATABASE -c $SK_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
